import os
import time

os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_final_ragan_vgg_relu4_3.py  --train --port=13002")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_final_ragan_vgg_relu4_3.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_final_ragan_vgg_relu4_3.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs64_BN_nonormDlayer5_3_final_ragan_lsgan_64D_PV_vgg_relu4_3.py --train --port=13002")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs64_BN_nonormDlayer5_3_final_ragan_lsgan_64D_PV_vgg_relu4_3.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs64_BN_nonormDlayer5_3_final_ragan_lsgan_64D_PV_vgg_relu4_3.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_3_final_ragan_lsgan_32D_PV_vgg_relu4_3.py --train --port=13002")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_3_final_ragan_lsgan_32D_PV_vgg_relu4_3.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_3_final_ragan_lsgan_32D_PV_vgg_relu4_3.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_4_final_ragan_lsgan_32D_PV_vgg_no_maxpool.py --train --port=13002")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_4_final_ragan_lsgan_32D_PV_vgg_no_maxpool.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_4_final_ragan_lsgan_32D_PV_vgg_no_maxpool.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_final_ragan_vgg_no_maxpool.py  --train --port=13002")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_final_ragan_vgg_no_maxpool.py --predict")
time.sleep(5)
os.system("CUDA_VISIBLE_DEVICES=0,4,3 python scripts/single_unet_conv_add_bs32_BN_nonormDlayer5_final_ragan_vgg_no_maxpool.py --predict")
time.sleep(5)